Ruby/NationBuilderService/config/routes.rb
NationBuilderMapsService::Application.routes.draw do

  resources :power_connections

  resources :power_relay_station_types

  resources :power_relay_stations

  resources :power_grid_nodes

  resources :node_types

  resources :militarystrongholds

  resources :warehouses

  resources :cities

  resources :claims

  resources :currencies

  

  resources :users

  resources :energy_buildings

  resources :energy_building_types

  resources :resources

  resources :terraintypes

  resources :resourcetypes

  resources :uploads

  resources :tiles 
  
  resources :layers

  resources :images

  resources :maps
  
  get '/tiles/find/:xposition/:yposition', to: 'tiles#find', as: 'tile1' 
  get '/users/names/:name', to: 'users#getuserbyname'
  get '/tiles/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'tiles#getscreen', as: 'tiles1' 
  get '/maps/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'maps#getscreen', as: 'map1'
  post '/maps/post/fetchsections', to: 'maps#fetchsections', as: 'fetchsections'
  get '/power_connections/fetch/connections', to: 'power_connections#fetchconnections', as: 'fetchconnections'
  post '/militarystrongholds/createnewbase', to: 'militarystrongholds#createnewbase', as: 'militarystrongholds1'
  get '/states/first', to: 'states#first', as: 'states1'
  resources :states

end

Ruby/NationBuilderService/app/models/building.rb
class Building < ActiveRecord::Base
has_one  :game_entity
belongs_to :tile
end

Ruby/NationBuilderService/app/models/city.rb
class City < ActiveRecord::Base
has_one  :game_entity
end

Ruby/NationBuilderService/app/models/claim.rb
class Claim < ActiveRecord::Base
belongs_to:state
belongs_to:tile
end

Ruby/NationBuilderService/app/models/currency.rb
class Currency < ActiveRecord::Base
has_many :states
end

Ruby/NationBuilderService/app/models/game_entity.rb
class GameEntity < ActiveRecord::Base
has_many :buildings
has_many :military_bases
end

Ruby/NationBuilderService/app/models/image.rb
class Image < ActiveRecord::Base
 has_many:tiles
end

Ruby/NationBuilderService/app/models/layer.rb
class Layer < ActiveRecord::Base
has_many :tiles
belongs_to :map
end

Ruby/NationBuilderService/app/models/map.rb
class Map < ActiveRecord::Base
has_many :layers
has_many :images
end

Ruby/NationBuilderService/app/models/node_type.rb
class NodeType < ActiveRecord::Base
belongs_to :power_grid_node
has_one :energy_building,  :foreign_key => "power_grid_node_id"
has_one :power_relay_station, :foreign_key => "power_grid_node_id"
end

Ruby/NationBuilderService/app/models/resource.rb
class Resource < ActiveRecord::Base
belongs_to :tile
belongs_to :resourcetype
end

Ruby/NationBuilderService/app/models/resourcetype.rb
class Resourcetype < ActiveRecord::Base
has_many :resourcetypes
end

Ruby/NationBuilderService/app/models/state.rb
class State < ActiveRecord::Base
has_one :currency
has_many :claims
end

Ruby/NationBuilderService/app/models/terraintype.rb
class Terraintype < ActiveRecord::Base
has_many :tiles
end

Ruby/NationBuilderService/app/models/tile.rb
class Tile < ActiveRecord::Base 
 belongs_to :layer 
 has_one :image
 has_one :resource
 has_many :claims
 has_one  :terraintype
 has_and_belongs_to_many :militarystrongholds
 has_many :resources	
 has_many :buildings
end

Ruby/NationBuilderService/app/models/tilesection.rb
class Tilesection
 include ActiveModel::Model
 
 attr_accessor:x
 attr_accessor:y
 
 attr_accessor:width
 attr_accessor:height
 
end

Ruby/NationBuilderService/app/models/tilestatus.rb
class Tilestatus
 include ActiveModel::Model
 
 attr_accessor:status
end

Ruby/NationBuilderService/app/models/upload.rb
class Upload < ActiveRecord::Base
end

Ruby/NationBuilderService/app/models/user.rb
class User < ActiveRecord::Base
has_one :state
end

Ruby/NationBuilderService/app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
has_one :building
belongs_to :buildings
end

Ruby/NationBuilderService/app/controllers/terraintypes_controller.rb
class TerraintypesController < ApplicationController
  before_action :set_terraintype, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :secret => 'salty_phrase',
		       :except => :create
  # GET /terraintypes
  def index
    @terraintypes = Terraintype.all
  end

  # GET /terraintypes/1
  def show
  end

  # GET /terraintypes/new
  def new
    @terraintype = Terraintype.new
  end

  # GET /terraintypes/1/edit
  def edit
  end

  # POST /terraintypes
  def create
    @terraintype = Terraintype.new(terraintype_params)
    respond_to do |format|
     if @terraintype.save
       format.html { redirect_to @terraintype, notice: 'Terraintype was successfully created.' }
       format.json { render action: 'id', status: :created, location: @terraintype }
     else
       render action: 'new'
     end
   end
  end

  # PATCH/PUT /terraintypes/1
  def update
    if @terraintype.update(terraintype_params)
      redirect_to @terraintype, notice: 'Terraintype was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /terraintypes/1
  def destroy
    @terraintype.destroy
    redirect_to terraintypes_url, notice: 'Terraintype was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_terraintype
      @terraintype = Terraintype.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def terraintype_params
      params.require(:terraintype).permit(:name)
    end
end

Ruby/NationBuilderService/app/helpers/maps_helper.rb
module MapsHelper
end

Ruby/NationBuilderService/app/helpers/terraintypes_helper.rb
module TerraintypesHelper
end

Ruby/NationBuilderService/app/views/terraintypes/_form.html.erb
<%= form_for(@terraintype) do |f| %>
  <% if @terraintype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@terraintype.errors.count, "error") %> prohibited this terraintype from being saved:</h2>

      <ul>
      <% @terraintype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/NationBuilderService/app/views/terraintypes/edit.html.erb
<h1>Editing terraintype</h1>

<%= render 'form' %>

<%= link_to 'Show', @terraintype %> |
<%= link_to 'Back', terraintypes_path %>

Ruby/NationBuilderService/app/views/terraintypes/index.html.erb
<h1>Listing terraintypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @terraintypes.each do |terraintype| %>
      <tr>
        <td><%= terraintype.name %></td>
        <td><%= link_to 'Show', terraintype %></td>
        <td><%= link_to 'Edit', edit_terraintype_path(terraintype) %></td>
        <td><%= link_to 'Destroy', terraintype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Terraintype', new_terraintype_path %>

Ruby/NationBuilderService/app/views/terraintypes/new.html.erb
<h1>New terraintype</h1>

<%= render 'form' %>

<%= link_to 'Back', terraintypes_path %>

Ruby/NationBuilderService/app/views/terraintypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @terraintype.name %>
</p>

<%= link_to 'Edit', edit_terraintype_path(@terraintype) %> |
<%= link_to 'Back', terraintypes_path %>