Ruby/NationBuilderService/config/routes.rb
NationBuilderMapsService::Application.routes.draw do

  resources :power_connections

  resources :power_relay_station_types

  resources :power_relay_stations

  resources :power_grid_nodes

  resources :node_types

  resources :militarystrongholds

  resources :warehouses

  resources :cities

  resources :claims

  resources :currencies

  

  resources :users

  resources :energy_buildings

  resources :energy_building_types

  resources :resources

  resources :terraintypes

  resources :resourcetypes

  resources :uploads

  resources :tiles 
  
  resources :layers

  resources :images

  resources :maps
  
  get '/tiles/find/:xposition/:yposition', to: 'tiles#find', as: 'tile1' 
  get '/users/names/:name', to: 'users#getuserbyname'
  get '/tiles/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'tiles#getscreen', as: 'tiles1' 
  get '/maps/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'maps#getscreen', as: 'map1'
  post '/maps/post/fetchsections', to: 'maps#fetchsections', as: 'fetchsections'
  get '/power_connections/fetch/connections', to: 'power_connections#fetchconnections', as: 'fetchconnections'
  post '/militarystrongholds/createnewbase', to: 'militarystrongholds#createnewbase', as: 'militarystrongholds1'
  get '/states/first', to: 'states#first', as: 'states1'
  resources :states

end

Ruby/NationBuilderService/app/models/building.rb
class Building < ActiveRecord::Base
has_one  :game_entity
belongs_to :tile
end

Ruby/NationBuilderService/app/models/city.rb
class City < ActiveRecord::Base
has_one  :game_entity
end

Ruby/NationBuilderService/app/models/claim.rb
class Claim < ActiveRecord::Base
belongs_to:state
belongs_to:tile
end

Ruby/NationBuilderService/app/models/currency.rb
class Currency < ActiveRecord::Base
has_many :states
end

Ruby/NationBuilderService/app/models/game_entity.rb
class GameEntity < ActiveRecord::Base
has_many :buildings
has_many :military_bases
end

Ruby/NationBuilderService/app/models/image.rb
class Image < ActiveRecord::Base
 has_many:tiles
end

Ruby/NationBuilderService/app/models/layer.rb
class Layer < ActiveRecord::Base
has_many :tiles
belongs_to :map
end

Ruby/NationBuilderService/app/models/map.rb
class Map < ActiveRecord::Base
has_many :layers
has_many :images
end

Ruby/NationBuilderService/app/models/node_type.rb
class NodeType < ActiveRecord::Base
belongs_to :power_grid_node
has_one :energy_building,  :foreign_key => "power_grid_node_id"
has_one :power_relay_station, :foreign_key => "power_grid_node_id"
end

Ruby/NationBuilderService/app/models/resource.rb
class Resource < ActiveRecord::Base
belongs_to :tile
belongs_to :resourcetype
end

Ruby/NationBuilderService/app/models/resourcetype.rb
class Resourcetype < ActiveRecord::Base
has_many :resourcetypes
end

Ruby/NationBuilderService/app/models/state.rb
class State < ActiveRecord::Base
has_one :currency
has_many :claims
end

Ruby/NationBuilderService/app/models/terraintype.rb
class Terraintype < ActiveRecord::Base
has_many :tiles
end

Ruby/NationBuilderService/app/models/tile.rb
class Tile < ActiveRecord::Base 
 belongs_to :layer 
 has_one :image
 has_one :resource
 has_many :claims
 has_one  :terraintype
 has_and_belongs_to_many :militarystrongholds
 has_many :resources	
 has_many :buildings
end

Ruby/NationBuilderService/app/models/tilesection.rb
class Tilesection
 include ActiveModel::Model
 
 attr_accessor:x
 attr_accessor:y
 
 attr_accessor:width
 attr_accessor:height
 
end

Ruby/NationBuilderService/app/models/tilestatus.rb
class Tilestatus
 include ActiveModel::Model
 
 attr_accessor:status
end

Ruby/NationBuilderService/app/models/upload.rb
class Upload < ActiveRecord::Base
end

Ruby/NationBuilderService/app/models/user.rb
class User < ActiveRecord::Base
has_one :state
end

Ruby/NationBuilderService/app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
has_one :building
belongs_to :buildings
end

Ruby/NationBuilderService/app/controllers/node_types_controller.rb
class NodeTypesController < ApplicationController
  before_action :set_node_type, only: [:show, :edit, :update, :destroy]
   protect_from_forgery :secret => 'salty_phrase',
		       :except => :create


  # GET /node_types
  def index
    @node_types = NodeType.all
  end

  # GET /node_types/1
  def show
  end

  # GET /node_types/new
  def new
    @node_type = NodeType.new
  end

  # GET /node_types/1/edit
  def edit
  end

  # POST /node_types
  def create
    @node_type = NodeType.new(node_type_params)

     respond_to do |format|
      if @node_type.save
        format.html { redirect_to @node_type, notice: 'Nodetype was successfully created.' }
        format.json { render action: 'id', status: :created, location: @state }
      else
        format.html { render action: 'new' }
        format.json { render json: @node_type.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # PATCH/PUT /node_types/1
  def update
    if @node_type.update(node_type_params)
      redirect_to @node_type, notice: 'Node type was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /node_types/1
  def destroy
    @node_type.destroy
    redirect_to node_types_url, notice: 'Node type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node_type
      @node_type = NodeType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def node_type_params
      params.require(:node_type).permit(:name, :destroyable)
    end
end

Ruby/NationBuilderService/app/helpers/maps_helper.rb
module MapsHelper
end

Ruby/NationBuilderService/app/helpers/node_types_helper.rb
module NodeTypesHelper
end

Ruby/NationBuilderService/app/views/node_types/_form.html.erb
<%= form_for(@node_type) do |f| %>
  <% if @node_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node_type.errors.count, "error") %> prohibited this node_type from being saved:</h2>

      <ul>
      <% @node_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :destroyable %><br>
    <%= f.text_field :destroyable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/NationBuilderService/app/views/node_types/edit.html.erb
<h1>Editing node_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @node_type %> |
<%= link_to 'Back', node_types_path %>

Ruby/NationBuilderService/app/views/node_types/index.html.erb
<h1>Listing node_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Destroyable</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @node_types.each do |node_type| %>
      <tr>
        <td><%= node_type.name %></td>
        <td><%= node_type.destroyable %></td>
        <td><%= link_to 'Show', node_type %></td>
        <td><%= link_to 'Edit', edit_node_type_path(node_type) %></td>
        <td><%= link_to 'Destroy', node_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node type', new_node_type_path %>

Ruby/NationBuilderService/app/views/node_types/new.html.erb
<h1>New node_type</h1>

<%= render 'form' %>

<%= link_to 'Back', node_types_path %>

Ruby/NationBuilderService/app/views/node_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node_type.name %>
</p>

<p>
  <strong>Destroyable:</strong>
  <%= @node_type.destroyable %>
</p>

<%= link_to 'Edit', edit_node_type_path(@node_type) %> |
<%= link_to 'Back', node_types_path %>