Ruby/NationBuilderService/config/routes.rb
NationBuilderMapsService::Application.routes.draw do

  resources :power_connections

  resources :power_relay_station_types

  resources :power_relay_stations

  resources :power_grid_nodes

  resources :node_types

  resources :militarystrongholds

  resources :warehouses

  resources :cities

  resources :claims

  resources :currencies

  

  resources :users

  resources :energy_buildings

  resources :energy_building_types

  resources :resources

  resources :terraintypes

  resources :resourcetypes

  resources :uploads

  resources :tiles 
  
  resources :layers

  resources :images

  resources :maps
  
  get '/tiles/find/:xposition/:yposition', to: 'tiles#find', as: 'tile1' 
  get '/users/names/:name', to: 'users#getuserbyname'
  get '/tiles/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'tiles#getscreen', as: 'tiles1' 
  get '/maps/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'maps#getscreen', as: 'map1'
  post '/maps/post/fetchsections', to: 'maps#fetchsections', as: 'fetchsections'
  get '/power_connections/fetch/connections', to: 'power_connections#fetchconnections', as: 'fetchconnections'
  post '/militarystrongholds/createnewbase', to: 'militarystrongholds#createnewbase', as: 'militarystrongholds1'
  get '/states/first', to: 'states#first', as: 'states1'
  resources :states

end

Ruby/NationBuilderService/app/models/building.rb
class Building < ActiveRecord::Base
has_one  :game_entity
belongs_to :tile
end

Ruby/NationBuilderService/app/models/city.rb
class City < ActiveRecord::Base
has_one  :game_entity
end

Ruby/NationBuilderService/app/models/claim.rb
class Claim < ActiveRecord::Base
belongs_to:state
belongs_to:tile
end

Ruby/NationBuilderService/app/models/currency.rb
class Currency < ActiveRecord::Base
has_many :states
end

Ruby/NationBuilderService/app/models/game_entity.rb
class GameEntity < ActiveRecord::Base
has_many :buildings
has_many :military_bases
end

Ruby/NationBuilderService/app/models/image.rb
class Image < ActiveRecord::Base
 has_many:tiles
end

Ruby/NationBuilderService/app/models/layer.rb
class Layer < ActiveRecord::Base
has_many :tiles
belongs_to :map
end

Ruby/NationBuilderService/app/models/map.rb
class Map < ActiveRecord::Base
has_many :layers
has_many :images
end

Ruby/NationBuilderService/app/models/node_type.rb
class NodeType < ActiveRecord::Base
belongs_to :power_grid_node
has_one :energy_building,  :foreign_key => "power_grid_node_id"
has_one :power_relay_station, :foreign_key => "power_grid_node_id"
end

Ruby/NationBuilderService/app/models/resource.rb
class Resource < ActiveRecord::Base
belongs_to :tile
belongs_to :resourcetype
end

Ruby/NationBuilderService/app/models/resourcetype.rb
class Resourcetype < ActiveRecord::Base
has_many :resourcetypes
end

Ruby/NationBuilderService/app/models/state.rb
class State < ActiveRecord::Base
has_one :currency
has_many :claims
end

Ruby/NationBuilderService/app/models/terraintype.rb
class Terraintype < ActiveRecord::Base
has_many :tiles
end

Ruby/NationBuilderService/app/models/tile.rb
class Tile < ActiveRecord::Base 
 belongs_to :layer 
 has_one :image
 has_one :resource
 has_many :claims
 has_one  :terraintype
 has_and_belongs_to_many :militarystrongholds
 has_many :resources	
 has_many :buildings
end

Ruby/NationBuilderService/app/models/tilesection.rb
class Tilesection
 include ActiveModel::Model
 
 attr_accessor:x
 attr_accessor:y
 
 attr_accessor:width
 attr_accessor:height
 
end

Ruby/NationBuilderService/app/models/tilestatus.rb
class Tilestatus
 include ActiveModel::Model
 
 attr_accessor:status
end

Ruby/NationBuilderService/app/models/upload.rb
class Upload < ActiveRecord::Base
end

Ruby/NationBuilderService/app/models/user.rb
class User < ActiveRecord::Base
has_one :state
end

Ruby/NationBuilderService/app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
has_one :building
belongs_to :buildings
end

Ruby/NationBuilderService/app/controllers/tiles_controller.rb
class TilesController < ApplicationController

  before_action :set_tile, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :secret => 'salty_phrase',
		       :except => :create
  # GET /tiles
  # GET /tiles.json
  def index
    @tiles = Tile.all
  end

  # GET /tiles/1
  # GET /tiles/1.json
  def show
  end

  # NOTE: deze getscreen methode wordt niet gebruikt blijkbaar, deze kan dus weg 
  def getscreen
  	 xposrange = params[:width]
	 yposrange = params[:height]  	 
  	 @tiles = Tile.find(:all,:conditions => 
  	 { :xposition => params[:centerpositionx]..xposrange,
  	   :yposition => params[:centerpositiony]..yposrange
  	 })

  end
  # GET /tiles/foo
  def find 
  @tile = Tile.joins("LEFT JOIN claims ON tiles.id = claims.tile_id").joins(:resource).where(xposition: params[:xposition],yposition: params[:yposition]).take
  
  end
  # GET /tiles/new
  def new
    @tile = Tile.new
  end

  # GET /tiles/1/edit
  def edit
  end

  # POST /tiles
  # POST /tiles.json
  def create
ActionController::Parameters.permit_all_parameters = true
    @tile = Tile.new(tile_params)

    if params[:imd] != nil
      @image = Image.find(params[:imd])
      @image.tiles << @tile
    end
    if params[:tti] != nil
		@terraintype = Terraintype.find(params[:tti])   
		@terraintype.tiles << @tile
		#@tile.terraintype = @terraintype 
    end
    if params[:lmd] != nil
      @layer = Layer.find(params[:lmd])
      @layer.tiles << @tile
    end

    if params[:rid] != nil
    	@resource = Resource.find(params[:rid])
	   @resource.tiles << @tile
	 end 
    if params[:rids] != nil
		params[:rids].each {	|x| 
	 	@resource = Resource.find(x)	 
	 	@tile.resources << @resource
		}
	end		
	if params[:bids] != nil
		params[:bids].each {	|x| 
	 	@building = Building.find(x)	 
	 	@tile.buildings << @building
		}
	end	
Rails.logger.debug "tile params: " + params[:imd].to_s
  
    respond_to do |format|

      if @tile.save 
        format.html { redirect_to @tile, notice: 'Tile was successfully created.' }
        format.json { render action: 'id', status: :created, location: @tile }
      else
        format.html { render action: 'new' }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiles/1
  # PATCH/PUT /tiles/1.json
  def update
    respond_to do |format|
      if @tile.update(tile_params)
        format.html { redirect_to @tile, notice: 'Tile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiles/1
  # DELETE /tiles/1.json
  def destroy
    @tile.destroy
    respond_to do |format|
      format.html { redirect_to tiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tile
      @tile = Tile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tile_params
      params.require(:tile).permit(:gidtag,:xposition, :yposition, :xoffset, :yoffset)
    end
end

Ruby/NationBuilderService/app/helpers/maps_helper.rb
module MapsHelper
end

Ruby/NationBuilderService/app/helpers/tiles_helper.rb
module TilesHelper
end

Ruby/NationBuilderService/app/helpers/users_helper.rb
module UsersHelper
end

Ruby/NationBuilderService/app/views/tiles/_form.html.erb
<%= form_for(@tile) do |f| %>
  <% if @tile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tile.errors.count, "error") %> prohibited this tile from being saved:</h2>

      <ul>
      <% @tile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xposition %><br>
    <%= f.number_field :xposition %>
  </div>
  <div class="field">
    <%= f.label :yposition %><br>
    <%= f.number_field :yposition %>
  </div>
  <div class="field">
    <%= f.label :xoffset %><br>
    <%= f.number_field :xoffset %>
  </div>
  <div class="field">
    <%= f.label :yoffset %><br>
    <%= f.number_field :yoffset %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/NationBuilderService/app/views/tiles/edit.html.erb
<h1>Editing tile</h1>

<%= render 'form' %>

<%= link_to 'Show', @tile %> |
<%= link_to 'Back', tiles_path %>

Ruby/NationBuilderService/app/views/tiles/index.html.erb
<h1>Listing tiles</h1>

<table>
  <thead>
    <tr>
      <th>Xposition</th>
      <th>Yposition</th>
      <th>Xoffset</th>
      <th>Yoffset</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tiles.each do |tile| %>
      <tr>
        <td><%= tile.xposition %></td>
        <td><%= tile.yposition %></td>
        <td><%= tile.xoffset %></td>
        <td><%= tile.yoffset %></td>
        <td><%= link_to 'Show', tile %></td>
        <td><%= link_to 'Edit', edit_tile_path(tile) %></td>
        <td><%= link_to 'Destroy', tile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tile', new_tile_path %>

Ruby/NationBuilderService/app/views/tiles/new.html.erb
<h1>New tile</h1>

<%= render 'form' %>

<%= link_to 'Back', tiles_path %>

Ruby/NationBuilderService/app/views/tiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xposition:</strong>
  <%= @tile.xposition %>
</p>

<p>
  <strong>Yposition:</strong>
  <%= @tile.yposition %>
</p>

<p>
  <strong>Xoffset:</strong>
  <%= @tile.xoffset %>
</p>

<p>
  <strong>Yoffset:</strong>
  <%= @tile.yoffset %>
</p>

<%= link_to 'Edit', edit_tile_path(@tile) %> |
<%= link_to 'Back', tiles_path %>