Ruby/NationBuilderService/config/routes.rb
NationBuilderMapsService::Application.routes.draw do

  resources :power_connections

  resources :power_relay_station_types

  resources :power_relay_stations

  resources :power_grid_nodes

  resources :node_types

  resources :militarystrongholds

  resources :warehouses

  resources :cities

  resources :claims

  resources :currencies

  

  resources :users

  resources :energy_buildings

  resources :energy_building_types

  resources :resources

  resources :terraintypes

  resources :resourcetypes

  resources :uploads

  resources :tiles 
  
  resources :layers

  resources :images

  resources :maps
  
  get '/tiles/find/:xposition/:yposition', to: 'tiles#find', as: 'tile1' 
  get '/users/names/:name', to: 'users#getuserbyname'
  get '/tiles/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'tiles#getscreen', as: 'tiles1' 
  get '/maps/getscreen/:centerpositionx/:centerpositiony/:width/:height', to: 'maps#getscreen', as: 'map1'
  post '/maps/post/fetchsections', to: 'maps#fetchsections', as: 'fetchsections'
  get '/power_connections/fetch/connections', to: 'power_connections#fetchconnections', as: 'fetchconnections'
  post '/militarystrongholds/createnewbase', to: 'militarystrongholds#createnewbase', as: 'militarystrongholds1'
  get '/states/first', to: 'states#first', as: 'states1'
  resources :states

end

Ruby/NationBuilderService/app/models/building.rb
class Building < ActiveRecord::Base
has_one  :game_entity
belongs_to :tile
end

Ruby/NationBuilderService/app/models/city.rb
class City < ActiveRecord::Base
has_one  :game_entity
end

Ruby/NationBuilderService/app/models/claim.rb
class Claim < ActiveRecord::Base
belongs_to:state
belongs_to:tile
end

Ruby/NationBuilderService/app/models/currency.rb
class Currency < ActiveRecord::Base
has_many :states
end

Ruby/NationBuilderService/app/models/game_entity.rb
class GameEntity < ActiveRecord::Base
has_many :buildings
has_many :military_bases
end

Ruby/NationBuilderService/app/models/image.rb
class Image < ActiveRecord::Base
 has_many:tiles
end

Ruby/NationBuilderService/app/models/layer.rb
class Layer < ActiveRecord::Base
has_many :tiles
belongs_to :map
end

Ruby/NationBuilderService/app/models/map.rb
class Map < ActiveRecord::Base
has_many :layers
has_many :images
end

Ruby/NationBuilderService/app/models/node_type.rb
class NodeType < ActiveRecord::Base
belongs_to :power_grid_node
has_one :energy_building,  :foreign_key => "power_grid_node_id"
has_one :power_relay_station, :foreign_key => "power_grid_node_id"
end

Ruby/NationBuilderService/app/models/resource.rb
class Resource < ActiveRecord::Base
belongs_to :tile
belongs_to :resourcetype
end

Ruby/NationBuilderService/app/models/resourcetype.rb
class Resourcetype < ActiveRecord::Base
has_many :resourcetypes
end

Ruby/NationBuilderService/app/models/state.rb
class State < ActiveRecord::Base
has_one :currency
has_many :claims
end

Ruby/NationBuilderService/app/models/terraintype.rb
class Terraintype < ActiveRecord::Base
has_many :tiles
end

Ruby/NationBuilderService/app/models/tile.rb
class Tile < ActiveRecord::Base 
 belongs_to :layer 
 has_one :image
 has_one :resource
 has_many :claims
 has_one  :terraintype
 has_and_belongs_to_many :militarystrongholds
 has_many :resources	
 has_many :buildings
end

Ruby/NationBuilderService/app/models/tilesection.rb
class Tilesection
 include ActiveModel::Model
 
 attr_accessor:x
 attr_accessor:y
 
 attr_accessor:width
 attr_accessor:height
 
end

Ruby/NationBuilderService/app/models/tilestatus.rb
class Tilestatus
 include ActiveModel::Model
 
 attr_accessor:status
end

Ruby/NationBuilderService/app/models/upload.rb
class Upload < ActiveRecord::Base
end

Ruby/NationBuilderService/app/models/user.rb
class User < ActiveRecord::Base
has_one :state
end

Ruby/NationBuilderService/app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
has_one :building
belongs_to :buildings
end

Ruby/NationBuilderService/app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :secret => 'salty_phrase',
		       :except => :create
  # GET /claims
  def index
    @claims = Claim.all
  end

  # GET /claims/1
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims
  def create
    @claim = Claim.new(claim_params)
    if params[:tile_id] != nil
      @tile = Tile.find(params[:tile_id])
      @tile.claims << @claim
    end
    if params[:state_id] != nil
      @state = State.find(params[:state_id])
      @state.claims << @claim
    end
    
    respond_to do |format|

      if @claim.save 
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render action: 'id', status: :created, location: @claim  }
      else
        format.html { render action: 'new' }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  def update
    if @claim.update(claim_params)
      redirect_to @claim, notice: 'Claim was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /claims/1
  def destroy
    @claim.destroy
    redirect_to claims_url, notice: 'Claim was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def claim_params
      params.require(:claim).permit(:tile_id, :state_id)
    end
end

Ruby/NationBuilderService/app/helpers/claims_helper.rb
module ClaimsHelper
end

Ruby/NationBuilderService/app/helpers/maps_helper.rb
module MapsHelper
end

Ruby/NationBuilderService/app/helpers/tiles_helper.rb
module TilesHelper
end

Ruby/NationBuilderService/app/views/claims/_form.html.erb
<%= form_for(@claim) do |f| %>
  <% if @claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

      <ul>
      <% @claim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tile_id %><br>
    <%= f.number_field :tile_id %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.number_field :state_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/NationBuilderService/app/views/claims/edit.html.erb
<h1>Editing claim</h1>

<%= render 'form' %>

<%= link_to 'Show', @claim %> |
<%= link_to 'Back', claims_path %>

Ruby/NationBuilderService/app/views/claims/index.html.erb
<h1>Listing claims</h1>

<table>
  <thead>
    <tr>
      <th>Tile</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= claim.tile_id %></td>
        <td><%= claim.state_id %></td>
        <td><%= link_to 'Show', claim %></td>
        <td><%= link_to 'Edit', edit_claim_path(claim) %></td>
        <td><%= link_to 'Destroy', claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claim', new_claim_path %>

Ruby/NationBuilderService/app/views/claims/new.html.erb
<h1>New claim</h1>

<%= render 'form' %>

<%= link_to 'Back', claims_path %>

Ruby/NationBuilderService/app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tile:</strong>
  <%= @claim.tile_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @claim.state_id %>
</p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>